# NumPy Function Reference — A Beginner's Guide

This notebook is a categorized reference of the most-used **NumPy** functions.
For each function you get: a short description, its **syntax with parameters**, and a
small **runnable example** with output.

> NumPy is huge (hundreds of functions). This guide covers the ~130 functions you will
> actually use 95% of the time, grouped so you can find them fast. Run any cell to see it work.

**Install / import**
```
pip install numpy
```
```python
import numpy as np
```


---
## 1. Creating Arrays
Functions that build new arrays from scratch, from lists, or from ranges.

### `np.array`

Create an ndarray from a list, tuple, or another array.

**Syntax:** `np.array(object, dtype=None, copy=True, ndmin=0)`

In [ ]:
import numpy as np

arr = np.array([1, 2, 3], dtype=float)
print(arr)

[1. 2. 3.]


### `np.asarray`

Convert input to an array. Unlike array(), it does NOT copy if input is already an ndarray.

**Syntax:** `np.asarray(a, dtype=None)`

In [ ]:
import numpy as np

print(np.asarray([1, 2, 3]))

[1 2 3]


### `np.zeros`

Return a new array filled with 0s of the given shape.

**Syntax:** `np.zeros(shape, dtype=float)`

In [ ]:
import numpy as np

print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


### `np.ones`

Return a new array filled with 1s of the given shape.

**Syntax:** `np.ones(shape, dtype=float)`

In [ ]:
import numpy as np

print(np.ones((2, 2), dtype=int))

[[1 1]
 [1 1]]


### `np.full`

Return a new array of given shape filled with a value you choose.

**Syntax:** `np.full(shape, fill_value, dtype=None)`

In [ ]:
import numpy as np

print(np.full((2, 2), 7))

[[7 7]
 [7 7]]


### `np.empty`

Return an array without initializing values (contents are garbage, fast to allocate).

**Syntax:** `np.empty(shape, dtype=float)`

In [ ]:
import numpy as np

a = np.empty((2, 2))
print(a.shape)

(2, 2)


### `np.zeros_like`

Return an array of zeros with the same shape & type as a given array.

**Syntax:** `np.zeros_like(a, dtype=None)`

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
print(np.zeros_like(x))

[[0 0]
 [0 0]]


### `np.ones_like`

Return an array of ones with the same shape & type as a given array.

**Syntax:** `np.ones_like(a, dtype=None)`

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
print(np.ones_like(x))

[[1 1]
 [1 1]]


### `np.full_like`

Return an array with the same shape as a, filled with a chosen value.

**Syntax:** `np.full_like(a, fill_value, dtype=None)`

In [ ]:
import numpy as np

x = np.array([1, 2, 3])
print(np.full_like(x, 9))

[9 9 9]


### `np.arange`

Return evenly spaced values within a range (like Python range but returns an array).

**Syntax:** `np.arange(start, stop, step, dtype=None)`

In [ ]:
import numpy as np

print(np.arange(0, 10, 2))

[0 2 4 6 8]


### `np.linspace`

Return 'num' evenly spaced numbers between start and stop (inclusive).

**Syntax:** `np.linspace(start, stop, num=50, endpoint=True)`

In [ ]:
import numpy as np

print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


### `np.logspace`

Return numbers evenly spaced on a log scale.

**Syntax:** `np.logspace(start, stop, num=50, base=10.0)`

In [ ]:
import numpy as np

print(np.logspace(0, 2, 3))

[  1.  10. 100.]


### `np.eye`

Return a 2-D identity-like array with 1s on a diagonal (k shifts the diagonal).

**Syntax:** `np.eye(N, M=None, k=0, dtype=float)`

In [ ]:
import numpy as np

print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### `np.identity`

Return a square n x n identity matrix.

**Syntax:** `np.identity(n, dtype=float)`

In [ ]:
import numpy as np

print(np.identity(2))

[[1. 0.]
 [0. 1.]]


### `np.diag`

Extract a diagonal, or construct a diagonal array from a 1-D input.

**Syntax:** `np.diag(v, k=0)`

In [ ]:
import numpy as np

print(np.diag([1, 2, 3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


### `np.meshgrid`

Return coordinate matrices from coordinate vectors (useful for grids/plots).

**Syntax:** `np.meshgrid(*xi, indexing='xy')`

In [ ]:
import numpy as np

x, y = np.meshgrid([1, 2, 3], [4, 5])
print(x)
print(y)

[[1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]]


### `np.fromiter`

Create a 1-D array from an iterable object.

**Syntax:** `np.fromiter(iterable, dtype, count=-1)`

In [ ]:
import numpy as np

print(np.fromiter((i*i for i in range(5)), dtype=int))

[ 0  1  4  9 16]


---
## 2. Inspecting Arrays (attributes)
These are *attributes*, not functions — you access them without parentheses.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shape   :", arr.shape)     # (rows, columns)
print("ndim    :", arr.ndim)      # number of dimensions
print("size    :", arr.size)      # total number of elements
print("dtype   :", arr.dtype)     # data type
print("itemsize:", arr.itemsize)  # bytes per element
print("T (transpose):\n", arr.T)

shape   : (2, 3)
ndim    : 2
size    : 6
dtype   : int64
itemsize: 8
T (transpose):
 [[1 4]
 [2 5]
 [3 6]]


---
## 3. Reshaping & Manipulating Arrays
Change the shape, flatten, join, split, or repeat arrays.

### `np.reshape`

Give an array a new shape without changing its data. Use -1 to auto-calc a dimension.

**Syntax:** `np.reshape(a, newshape)`

In [ ]:
import numpy as np

a = np.arange(6)
print(a.reshape(2, 3))

[[0 1 2]
 [3 4 5]]


### `np.ravel`

Flatten an array to 1-D (returns a view when possible).

**Syntax:** `np.ravel(a)`

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(np.ravel(a))

[1 2 3 4]


### `np.flatten`

Flatten to 1-D — always returns a COPY (method on the array).

**Syntax:** `ndarray.flatten(order='C')`

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a.flatten())

[1 2 3 4]


### `np.transpose`

Permute the dimensions (swap rows and columns for 2-D).

**Syntax:** `np.transpose(a, axes=None)`

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.transpose(a))

[[1 4]
 [2 5]
 [3 6]]


### `np.swapaxes`

Interchange two axes of an array.

**Syntax:** `np.swapaxes(a, axis1, axis2)`

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(np.swapaxes(a, 0, 1))

[[1 3]
 [2 4]]


### `np.expand_dims`

Insert a new axis (increase dimensions by one).

**Syntax:** `np.expand_dims(a, axis)`

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(np.expand_dims(a, axis=0).shape)

(1, 3)


### `np.squeeze`

Remove axes of length 1 from the shape.

**Syntax:** `np.squeeze(a, axis=None)`

In [ ]:
import numpy as np

a = np.array([[[1], [2], [3]]])
print(np.squeeze(a).shape)

(3,)


### `np.concatenate`

Join a sequence of arrays along an existing axis.

**Syntax:** `np.concatenate((a1, a2, ...), axis=0)`

In [ ]:
import numpy as np

a = np.array([1, 2]); b = np.array([3, 4])
print(np.concatenate((a, b)))

[1 2 3 4]


### `np.stack`

Join arrays along a NEW axis.

**Syntax:** `np.stack(arrays, axis=0)`

In [ ]:
import numpy as np

a = np.array([1, 2]); b = np.array([3, 4])
print(np.stack((a, b), axis=0))

[[1 2]
 [3 4]]


### `np.vstack`

Stack arrays vertically (row-wise).

**Syntax:** `np.vstack(tup)`

In [ ]:
import numpy as np

a = np.array([1, 2, 3]); b = np.array([4, 5, 6])
print(np.vstack((a, b)))

[[1 2 3]
 [4 5 6]]


### `np.hstack`

Stack arrays horizontally (column-wise).

**Syntax:** `np.hstack(tup)`

In [ ]:
import numpy as np

a = np.array([1, 2, 3]); b = np.array([4, 5, 6])
print(np.hstack((a, b)))

[1 2 3 4 5 6]


### `np.split`

Split an array into multiple equal sub-arrays.

**Syntax:** `np.split(ary, indices_or_sections, axis=0)`

In [ ]:
import numpy as np

a = np.arange(6)
print(np.split(a, 3))

[array([0, 1]), array([2, 3]), array([4, 5])]


### `np.hsplit`

Split an array horizontally (column-wise).

**Syntax:** `np.hsplit(ary, indices_or_sections)`

In [ ]:
import numpy as np

a = np.arange(6).reshape(2, 3)
print(np.hsplit(a, 3))

[array([[0],
       [3]]), array([[1],
       [4]]), array([[2],
       [5]])]


### `np.append`

Append values to the end of an array (returns a new array).

**Syntax:** `np.append(arr, values, axis=None)`

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(np.append(a, [4, 5]))

[1 2 3 4 5]


### `np.insert`

Insert values at a given index.

**Syntax:** `np.insert(arr, obj, values, axis=None)`

In [ ]:
import numpy as np

a = np.array([1, 2, 4])
print(np.insert(a, 2, 3))

[1 2 3 4]


### `np.delete`

Return a new array with elements at given index removed.

**Syntax:** `np.delete(arr, obj, axis=None)`

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(np.delete(a, 1))

[1 3 4]


### `np.resize`

Return a new array of the given shape, repeating data if needed.

**Syntax:** `np.resize(a, new_shape)`

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(np.resize(a, (2, 3)))

[[1 2 3]
 [1 2 3]]


### `np.tile`

Repeat a whole array a given number of times.

**Syntax:** `np.tile(A, reps)`

In [ ]:
import numpy as np

a = np.array([1, 2])
print(np.tile(a, 3))

[1 2 1 2 1 2]


### `np.repeat`

Repeat each element of an array.

**Syntax:** `np.repeat(a, repeats, axis=None)`

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(np.repeat(a, 2))

[1 1 2 2 3 3]


### `np.flip`

Reverse the order of elements along an axis.

**Syntax:** `np.flip(m, axis=None)`

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(np.flip(a))

[3 2 1]


### `np.roll`

Shift elements along an axis (wraps around).

**Syntax:** `np.roll(a, shift, axis=None)`

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(np.roll(a, 1))

[4 1 2 3]


### `np.unique`

Find the sorted unique elements of an array.

**Syntax:** `np.unique(ar, return_counts=False)`

In [ ]:
import numpy as np

a = np.array([1, 2, 2, 3, 3, 3])
print(np.unique(a, return_counts=True))

(array([1, 2, 3]), array([1, 2, 3]))


---
## 4. Mathematical Operations
Element-wise arithmetic and common math functions.

### `np.add`

Element-wise addition (same as x1 + x2).

**Syntax:** `np.add(x1, x2)`

In [ ]:
import numpy as np

print(np.add([1, 2, 3], [4, 5, 6]))

[5 7 9]


### `np.subtract`

Element-wise subtraction.

**Syntax:** `np.subtract(x1, x2)`

In [ ]:
import numpy as np

print(np.subtract([5, 7, 9], [1, 2, 3]))

[4 5 6]


### `np.multiply`

Element-wise multiplication.

**Syntax:** `np.multiply(x1, x2)`

In [ ]:
import numpy as np

print(np.multiply([1, 2, 3], [4, 5, 6]))

[ 4 10 18]


### `np.divide`

Element-wise division.

**Syntax:** `np.divide(x1, x2)`

In [ ]:
import numpy as np

print(np.divide([10, 20, 30], [2, 4, 5]))

[5. 5. 6.]


### `np.power`

Raise elements of x1 to powers in x2.

**Syntax:** `np.power(x1, x2)`

In [ ]:
import numpy as np

print(np.power([2, 3, 4], 2))

[ 4  9 16]


### `np.mod`

Element-wise remainder (modulo).

**Syntax:** `np.mod(x1, x2)`

In [ ]:
import numpy as np

print(np.mod([10, 11, 12], 3))

[1 2 0]


### `np.sqrt`

Element-wise square root.

**Syntax:** `np.sqrt(x)`

In [ ]:
import numpy as np

print(np.sqrt([1, 4, 9, 16]))

[1. 2. 3. 4.]


### `np.exp`

Element-wise exponential (e**x).

**Syntax:** `np.exp(x)`

In [ ]:
import numpy as np

print(np.exp([0, 1]))

[1.         2.71828183]


### `np.log`

Natural logarithm (base e). Also np.log2, np.log10.

**Syntax:** `np.log(x)`

In [ ]:
import numpy as np

print(np.log([1, np.e]))

[0. 1.]


### `np.abs`

Element-wise absolute value.

**Syntax:** `np.abs(x)`

In [ ]:
import numpy as np

print(np.abs([-1, -2, 3]))

[1 2 3]


### `np.round`

Round to the given number of decimals.

**Syntax:** `np.round(a, decimals=0)`

In [ ]:
import numpy as np

print(np.round([1.234, 5.678], 1))

[1.2 5.7]


### `np.floor`

Round down to the nearest integer.

**Syntax:** `np.floor(x)`

In [ ]:
import numpy as np

print(np.floor([1.7, 2.3, -1.2]))

[ 1.  2. -2.]


### `np.ceil`

Round up to the nearest integer.

**Syntax:** `np.ceil(x)`

In [ ]:
import numpy as np

print(np.ceil([1.2, 2.7, -1.8]))

[ 2.  3. -1.]


### `np.cumsum`

Cumulative sum of elements.

**Syntax:** `np.cumsum(a, axis=None)`

In [ ]:
import numpy as np

print(np.cumsum([1, 2, 3, 4]))

[ 1  3  6 10]


### `np.cumprod`

Cumulative product of elements.

**Syntax:** `np.cumprod(a, axis=None)`

In [ ]:
import numpy as np

print(np.cumprod([1, 2, 3, 4]))

[ 1  2  6 24]


### `np.sin`

Element-wise sine (x in radians). Also cos, tan, arcsin, etc.

**Syntax:** `np.sin(x)`

In [ ]:
import numpy as np

print(np.round(np.sin([0, np.pi/2]), 2))

[0. 1.]


### `np.deg2rad`

Convert degrees to radians (np.radians does the same).

**Syntax:** `np.deg2rad(x)`

In [ ]:
import numpy as np

print(np.deg2rad([0, 90, 180]))

[0.         1.57079633 3.14159265]


---
## 5. Statistics & Aggregation
Summaries across a whole array or along an axis.

### `np.sum`

Sum of array elements (optionally along an axis).

**Syntax:** `np.sum(a, axis=None)`

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(np.sum(a), np.sum(a, axis=0))

10 [4 6]


### `np.prod`

Product of array elements.

**Syntax:** `np.prod(a, axis=None)`

In [ ]:
import numpy as np

print(np.prod([1, 2, 3, 4]))

24


### `np.min`

Minimum value. (np.max for maximum.)

**Syntax:** `np.min(a, axis=None)`

In [ ]:
import numpy as np

print(np.min([3, 1, 2]), np.max([3, 1, 2]))

1 3


### `np.mean`

Arithmetic mean (average).

**Syntax:** `np.mean(a, axis=None)`

In [ ]:
import numpy as np

print(np.mean([1, 2, 3, 4]))

2.5


### `np.median`

Median (middle value).

**Syntax:** `np.median(a, axis=None)`

In [ ]:
import numpy as np

print(np.median([1, 2, 3, 4, 5]))

3.0


### `np.average`

Weighted average.

**Syntax:** `np.average(a, weights=None)`

In [ ]:
import numpy as np

print(np.average([1, 2, 3], weights=[1, 1, 2]))

2.25


### `np.std`

Standard deviation (spread of data).

**Syntax:** `np.std(a, axis=None)`

In [ ]:
import numpy as np

print(np.round(np.std([1, 2, 3, 4]), 3))

1.118


### `np.var`

Variance (square of standard deviation).

**Syntax:** `np.var(a, axis=None)`

In [ ]:
import numpy as np

print(np.var([1, 2, 3, 4]))

1.25


### `np.percentile`

Compute the q-th percentile.

**Syntax:** `np.percentile(a, q, axis=None)`

In [ ]:
import numpy as np

print(np.percentile([1, 2, 3, 4], 50))

2.5


### `np.ptp`

Range: peak-to-peak (max - min).

**Syntax:** `np.ptp(a, axis=None)`

In [ ]:
import numpy as np

print(np.ptp([1, 5, 3]))

4


### `np.argmin`

Index of the minimum value. (np.argmax for maximum.)

**Syntax:** `np.argmin(a, axis=None)`

In [ ]:
import numpy as np

print(np.argmin([3, 1, 2]), np.argmax([3, 1, 2]))

1 0


### `np.corrcoef`

Pearson correlation coefficient matrix.

**Syntax:** `np.corrcoef(x, y=None)`

In [ ]:
import numpy as np

print(np.corrcoef([1, 2, 3], [2, 4, 6]))

[[1. 1.]
 [1. 1.]]


---
## 6. Logic, Comparison & Conditions
Boolean tests and conditional selection.

### `np.where`

Return elements from x where condition is True, else from y. With one arg, returns indices.

**Syntax:** `np.where(condition, x, y)`

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(np.where(a > 2, a, 0))

[0 0 3 4]


### `np.all`

Test whether ALL elements are True.

**Syntax:** `np.all(a, axis=None)`

In [ ]:
import numpy as np

print(np.all([True, True, False]))

False


### `np.any`

Test whether ANY element is True.

**Syntax:** `np.any(a, axis=None)`

In [ ]:
import numpy as np

print(np.any([False, False, True]))

True


### `np.greater`

Element-wise x1 > x2. (Also less, equal, not_equal.)

**Syntax:** `np.greater(x1, x2)`

In [ ]:
import numpy as np

print(np.greater([1, 5, 3], [2, 2, 2]))

[False  True  True]


### `np.logical_and`

Element-wise logical AND. (Also logical_or, logical_not.)

**Syntax:** `np.logical_and(x1, x2)`

In [ ]:
import numpy as np

print(np.logical_and([True, False], [True, True]))

[ True False]


### `np.isnan`

Test element-wise for NaN (Not a Number).

**Syntax:** `np.isnan(x)`

In [ ]:
import numpy as np

print(np.isnan([1.0, np.nan, 3.0]))

[False  True False]


### `np.clip`

Limit values to a range: anything below a_min becomes a_min, above a_max becomes a_max.

**Syntax:** `np.clip(a, a_min, a_max)`

In [ ]:
import numpy as np

print(np.clip([1, 5, 10, -2], 0, 6))

[1 5 6 0]


---
## 7. Sorting & Searching

### `np.sort`

Return a sorted copy of an array.

**Syntax:** `np.sort(a, axis=-1, kind='quicksort')`

In [ ]:
import numpy as np

print(np.sort([3, 1, 2]))

[1 2 3]


### `np.argsort`

Return the indices that would sort an array.

**Syntax:** `np.argsort(a, axis=-1)`

In [ ]:
import numpy as np

print(np.argsort([3, 1, 2]))

[1 2 0]


### `np.searchsorted`

Find indices where elements should be inserted to keep order.

**Syntax:** `np.searchsorted(a, v, side='left')`

In [ ]:
import numpy as np

print(np.searchsorted([1, 2, 4, 5], 3))

2


### `np.nonzero`

Return the indices of non-zero elements.

**Syntax:** `np.nonzero(a)`

In [ ]:
import numpy as np

print(np.nonzero([0, 3, 0, 5]))

(array([1, 3]),)


### `np.count_nonzero`

Count the number of non-zero values.

**Syntax:** `np.count_nonzero(a, axis=None)`

In [ ]:
import numpy as np

print(np.count_nonzero([0, 1, 2, 0, 3]))

3


### `np.extract`

Return elements that satisfy a condition.

**Syntax:** `np.extract(condition, arr)`

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(np.extract(a > 2, a))

[3 4]


---
## 8. Set Operations
Treat arrays like mathematical sets.

### `np.intersect1d`

Return the sorted, unique values that are in BOTH arrays.

**Syntax:** `np.intersect1d(ar1, ar2)`

In [ ]:
import numpy as np

print(np.intersect1d([1, 2, 3], [2, 3, 4]))

[2 3]


### `np.union1d`

Return the sorted, unique values from EITHER array.

**Syntax:** `np.union1d(ar1, ar2)`

In [ ]:
import numpy as np

print(np.union1d([1, 2], [2, 3]))

[1 2 3]


### `np.setdiff1d`

Values in ar1 that are NOT in ar2.

**Syntax:** `np.setdiff1d(ar1, ar2)`

In [ ]:
import numpy as np

print(np.setdiff1d([1, 2, 3], [2]))

[1 3]


### `np.in1d`

Test whether each element of ar1 is also in ar2.

**Syntax:** `np.in1d(ar1, ar2)`

In [ ]:
import numpy as np

print(np.in1d([1, 2, 3], [2, 3]))

[False  True  True]


---
## 9. Linear Algebra
Matrix math. Many live under the `np.linalg` sub-module.

### `np.dot`

Dot product of two arrays (matrix multiplication for 2-D).

**Syntax:** `np.dot(a, b)`

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]]); b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


### `np.matmul`

Matrix product of two arrays.

**Syntax:** `np.matmul(a, b)  # or a @ b`

In [ ]:
import numpy as np

a = np.array([[1, 0], [0, 1]]); b = np.array([[4, 1], [2, 2]])
print(a @ b)

[[4 1]
 [2 2]]


### `np.inner`

Inner product of two arrays.

**Syntax:** `np.inner(a, b)`

In [ ]:
import numpy as np

print(np.inner([1, 2, 3], [4, 5, 6]))

32


### `np.cross`

Cross product of two 3-element vectors.

**Syntax:** `np.cross(a, b)`

In [ ]:
import numpy as np

print(np.cross([1, 0, 0], [0, 1, 0]))

[0 0 1]


### `np.linalg.inv`

Inverse of a square matrix.

**Syntax:** `np.linalg.inv(a)`

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


### `np.linalg.det`

Determinant of a square matrix.

**Syntax:** `np.linalg.det(a)`

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(round(np.linalg.det(a), 2))

-2.0


### `np.linalg.eig`

Eigenvalues and eigenvectors of a square matrix.

**Syntax:** `np.linalg.eig(a)`

In [ ]:
import numpy as np

a = np.array([[2, 0], [0, 3]])
vals, vecs = np.linalg.eig(a)
print(vals)

[2. 3.]


### `np.linalg.solve`

Solve a linear system a·x = b for x.

**Syntax:** `np.linalg.solve(a, b)`

In [ ]:
import numpy as np

a = np.array([[3, 1], [1, 2]]); b = np.array([9, 8])
print(np.linalg.solve(a, b))

[2. 3.]


### `np.linalg.norm`

Vector or matrix norm (length/magnitude).

**Syntax:** `np.linalg.norm(x, ord=None)`

In [ ]:
import numpy as np

print(np.linalg.norm([3, 4]))

5.0


---
## 10. Random Numbers
From the `np.random` module. `seed()` makes results reproducible.

### `np.random.seed`

Set the random seed so results are reproducible.

**Syntax:** `np.random.seed(n)`

In [ ]:
import numpy as np

np.random.seed(0)
print(np.random.randint(100))

44


### `np.random.rand`

Random floats in [0, 1) of the given shape.

**Syntax:** `np.random.rand(d0, d1, ...)`

In [ ]:
import numpy as np

np.random.seed(1)
print(np.random.rand(3))

[4.17022005e-01 7.20324493e-01 1.14374817e-04]


### `np.random.randint`

Random integers from low (inclusive) to high (exclusive).

**Syntax:** `np.random.randint(low, high=None, size=None)`

In [ ]:
import numpy as np

np.random.seed(2)
print(np.random.randint(1, 10, size=5))

[9 9 7 3 9]


### `np.random.randn`

Random floats from the standard normal distribution.

**Syntax:** `np.random.randn(d0, d1, ...)`

In [ ]:
import numpy as np

np.random.seed(3)
print(np.round(np.random.randn(3), 2))

[1.79 0.44 0.1 ]


### `np.random.choice`

Random sample(s) from a 1-D array.

**Syntax:** `np.random.choice(a, size=None, replace=True, p=None)`

In [ ]:
import numpy as np

np.random.seed(4)
print(np.random.choice([10, 20, 30], size=4))

[30 30 20 20]


### `np.random.uniform`

Random floats from a uniform distribution over [low, high).

**Syntax:** `np.random.uniform(low=0.0, high=1.0, size=None)`

In [ ]:
import numpy as np

np.random.seed(5)
print(np.round(np.random.uniform(1, 5, 3), 2))

[1.89 4.48 1.83]


### `np.random.normal`

Random samples from a normal (Gaussian) distribution.

**Syntax:** `np.random.normal(loc=0.0, scale=1.0, size=None)`

In [ ]:
import numpy as np

np.random.seed(6)
print(np.round(np.random.normal(0, 1, 3), 2))

[-0.31  0.73  0.22]


### `np.random.shuffle`

Shuffle an array IN PLACE (modifies the original).

**Syntax:** `np.random.shuffle(x)`

In [ ]:
import numpy as np

np.random.seed(7)
a = np.array([1, 2, 3, 4, 5])
np.random.shuffle(a)
print(a)

[1 4 3 2 5]


### `np.random.permutation`

Return a shuffled COPY (original stays unchanged).

**Syntax:** `np.random.permutation(x)`

In [ ]:
import numpy as np

np.random.seed(8)
print(np.random.permutation([1, 2, 3, 4, 5]))

[5 3 2 1 4]


---
## 11. Saving & Loading Arrays
Persist arrays to disk and read them back.

### `np.save`

Save one array to a binary .npy file.

**Syntax:** `np.save(file, arr)`

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
np.save('/tmp/myarr.npy', a)
print('saved')

saved


### `np.load`

Load an array back from a .npy file.

**Syntax:** `np.load(file)`

In [ ]:
import numpy as np

print(np.load('/tmp/myarr.npy'))

[1 2 3]


### `np.savetxt`

Save an array to a text/CSV file.

**Syntax:** `np.savetxt(fname, X, delimiter=' ')`

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
np.savetxt('/tmp/data.csv', a, delimiter=',')
print('saved')

saved


### `np.loadtxt`

Load data from a text/CSV file.

**Syntax:** `np.loadtxt(fname, delimiter=None)`

In [ ]:
import numpy as np

print(np.loadtxt('/tmp/data.csv', delimiter=','))

[[1. 2.]
 [3. 4.]]
